import RecoilRootProvider from "./RecoilRootProvider";
import { jua } from "@/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <RecoilRootProvider>
      <html lang="en">
        <body className = {jua.className} style={{ margin: "0" }}>
          {children}
        </body>
      </html>
    </RecoilRootProvider>
  );
}
