import { Inter } from "next/font/google";
import localFont from "next/font/local";
import RecoilRootProvider from "./RecoilRootProvider";

export const inter = Inter({ subsets: ["latin"] });

const pretendard = localFont({
  src: "./PretendardVariable.ttf",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <RecoilRootProvider>
      <html lang="en">
        <body className={pretendard.className} style={{ margin: "0" }}>
          {children}
        </body>
      </html>
    </RecoilRootProvider>
  );
}
